# Generated by Django 6.0 on 2026-01-03 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 1, 3, 15, 52, 49, 481007)
            ),
        ),
    ]
