# Generated by Django 6.0 on 2026-01-05 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 1, 5, 17, 33, 47, 559840)
            ),
        ),
    ]
