# Generated by Django 6.0 on 2026-01-08 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 1, 8, 12, 42, 53, 42916)
            ),
        ),
    ]
