# Generated by Django 6.0 on 2026-01-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User_Accounts",
            fields=[
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
